Source/NomNom/Controllers/GioHangController.cs
using NomNom.Common;
using NomNom.DAL;
using NomNom.Models.GioHangs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NomNom.Controllers
{
    public class GioHangController : BaseController
    {
        // GET: GioHang
        public ActionResult Index()
        {
            var session = Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var user = (UserLogin)session;
                var dal = new GioHangDAL();
                return View(dal.GetGioHang(user.UserID));
            }
            return Redirect("/Home");
        }
        public JsonResult SoLuong()
        {
            var session = Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var user = (UserLogin)session;
                var dal = new GioHangDAL();
                var rs = dal.SoLuong(user.UserID);
                return Json(new
                {
                    data = rs
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new
            {
                data = 0
            }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Them(int SanPhamID)
        {
            var session = Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var user = (UserLogin)session;
                var dal = new GioHangDAL();
                var input = new GioHang();
                input.SanPhamID = SanPhamID;
                input.TaiKhoanID = user.UserID;
                input.SoLuong = 1;
                var rs = dal.Add(input);
                return Json(new
                {
                    status = rs
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new
            {
                status = CommonConstants.GIO_HANG_THEM_THAT_BAI
            }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UpdateSoLuong(int SanPhamID,int SoLuong)
        {
            var session = Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var user = (UserLogin)session;
                var dal = new GioHangDAL();
                var input = new GioHang();
                input.SanPhamID = SanPhamID;
                input.TaiKhoanID = user.UserID;
                input.SoLuong = SoLuong;
                var rs = dal.UpdateSoLuong(input);
                return Json(new
                {
                    status = rs
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new
            {
                status = 0
            }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Remove(int SanPhamID)
        {
            var session = Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var user = (UserLogin)session;
                var dal = new GioHangDAL();
                var rs = dal.Remove(user.UserID, SanPhamID);
                return Json(new
                {
                    status = rs
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new
            {
                status = 1
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

Source/NomNom/Controllers/SanPhamController.cs
using Newtonsoft.Json;
using NomNom.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NomNom.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult Index(string Ten)
        {
            if (Ten != null)
            {
                ViewBag.FilterTen = Ten;
            }
            var lspDAL = new LoaiSanPhamDAL();
            var thDAL = new ThuongHieuDAL();
            ViewBag.listLoaiSanPham = lspDAL.GetLoaiSanPham(null);
            ViewBag.listThuongHieu = thDAL.GetThuongHieu(null);
            return View();
        }
        public ActionResult ChiTiet(int Id)
        {
            var dal = new SanPhamDAL();
            var input = dal.GetForView(Id);
            if (input != null)
            {
                dal.Tang1View(Id);
                return View(input);
            }
            return Redirect("/SanPham");
            
        }
        [HttpGet]
        public JsonResult LoadData(string jsonFilter)
        {
            dynamic stuff = JsonConvert.DeserializeObject(jsonFilter);
            var lsp = new List<int>();
            var th = new List<int>();
            var ten = new List<string>();
            var count = (int)stuff.spCount;
            foreach(var item in stuff.LoaiSanPham)
            {
                lsp.Add((int)item);
            }
            foreach (var item in stuff.ThuongHieu)
            {
                th.Add((int)item);
            }
            foreach (var item in stuff.Ten)
            {
                ten.Add((string)item);
            }
            var dal = new SanPhamDAL();
            var result = dal.GetSanPhamArr(lsp,th,ten,count);
            return Json(new
            {
                data = result
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

Source/NomNom/Views/Shared/Header.cshtml
 <!-- Header section -->
<header class="header-section">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 text-center text-lg-left">
                    <!-- logo -->
                    <a href="@Url.Action("Index","Home")" class="site-logo">
                        <img src="~/Images/logo.png" alt="">
                    </a>
                </div>
                <div class="col-xl-6 col-lg-5">
                    <form class="header-search-form">
                        <input type="text" placeholder="Tìm kiếm sản phẩm ....">
                        <button><i class="flaticon-search"></i></button>
                    </form>
                </div>
                <div class="col-xl-4 col-lg-5">
                    <div class="user-panel">
                        <div class="up-item">
                            <i class="flaticon-profile"></i>
                            @Html.Partial("_LoginPartial")
                        </div>
                        <div class="up-item">
                            <div class="shopping-card">
                                <i class="flaticon-bag"></i>
                                @*<span>0</span>*@
                            </div>
                            <a href="@Url.Action("Index","GioHang")">Giỏ hàng</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="main-navbar">
        <div class="container">
            <!-- menu -->
            <ul class="main-menu">
                <li><a href="#">Trang chủ</a></li>
                <li>@Html.ActionLink("Sản phẩm", "Index", "SanPham")</li>
                
            </ul>
        </div>
    </nav>
</header>
<!-- Header section end -->

Source/NomNom/Views/Shared/_Layout.cshtml
<head>
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta name="description" content=" Divisima | eCommerce Template">
    <meta name="keywords" content="divisima, eCommerce, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/assets/client/img/favicon.ico" rel="shortcut icon" />
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="~/Assets/client/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Assets/client/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Assets/client/css/flaticon.css" />
    <link rel="stylesheet" href="~/Assets/client/css/slicknav.min.css" />
    <link rel="stylesheet" href="~/Assets/client/css/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/Assets/client/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/Assets/client/css/animate.css" />
    <link rel="stylesheet" href="~/Assets/client/css/style.css" />
</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header section -->
    <header class="header-section">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 text-center text-lg-left">
                        <!-- logo -->
                        <a href="~/Home/Index" class="site-logo">
                            <img src="~/assets/filesimages/NomNomTrueLogo.png" alt="">
                        </a>
                    </div>
                    <div class="col-xl-6 col-lg-5">
                        <form class="header-search-form">
                            <input id="txtTen" type="text" placeholder="Tìm kiếm sản phẩm...">
                            <button onclick="search(event)"><i class="flaticon-search"></i></button>
                        </form>
                    </div>
                    <div class="col-xl-4 col-lg-5">
                        <div class="user-panel">
                            <div class="up-item">

                                @if (HttpContext.Current.Session[NomNom.Common.CommonConstants.USER_SESSION] != null)
                                {
                                    <ul class="main-menu">
                                        <li>
                                            <a>
                                                <i class="flaticon-profile"></i>
                                                <span>Chào @(((NomNom.Common.UserLogin)(HttpContext.Current.Session[NomNom.Common.CommonConstants.USER_SESSION])).Name)</span>
                                                <img class="img-profile rounded-circle" style="width:40px" src="@(((NomNom.Common.UserLogin)(HttpContext.Current.Session[NomNom.Common.CommonConstants.USER_SESSION])).Avatar)">
                                            </a>
                                            <ul class="sub-menu">
                                                <li><a href="/TaiKhoan">Thông tin tài khoản</a></li>
                                                <li><a href="/DonHang">Đơn hàng của bạn</a></li>
                                                <li><a href="/GioHang">Giỏ hàng</a></li>
                                                <li><a data-toggle="modal" data-target="#logoutModal">Đăng xuất</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                }
                                else
                                {
                                    <a href="~/DangNhap">Đăng nhập</a> <a> hoặc </a> <a href="~/DangKy">Đăng ký</a>
                                }

                            </div>
                            <div class="up-item">
                                <div class="shopping-card">
                                    <i class="flaticon-bag"></i>
                                    <span id="spCount">0</span>
                                </div>
                                <a href="/GioHang">Giỏ hàng</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <nav class="main-navbar">
            <div class="container">
                <!-- menu -->
                <ul class="main-menu">
                    <li><a href="~/Home/Index">Trang chủ</a></li>
                    <li><a href="~/TinTuc">Tin tức</a></li>
                    <li><a href="~/SanPham/Index">Sản phẩm</a></li>
                    <li><a href="~/Home/LienHe">Liên hệ</a></li>
                   

                </ul>
            </div>
        </nav>
    </header>
    <!-- Header section end -->
    @RenderBody()
    <!-- Footer section -->
    @*<section class="footer-section">
            <div class="container">
                <div class="footer-logo text-center">
                    <a href="~/Home/Index"><img src="~/Assets/client/img/NomNomLogo.png" style="height:200px"alt=""></a>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <div class="footer-widget about-widget">
                            <h2>About</h2>
                            <p>Website thực phẩm sạch online</p>
                        </div>
                    </div>


                </div>
            </div>
            <div class="social-links-warp">
                <div class="container">
                    <div class="social-links">
                        <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
                        <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
                        <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
                        <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
                        <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
                        <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
                        <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
                    </div>

                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p class="text-white text-center mt-5">
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    </p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

                </div>
            </div>
        </section>*@
    <script src="~/Assets/client/js/jquery-3.2.1.min.js"></script>
    <script src="~/Assets/client/js/bootstrap.min.js"></script>
    <script src="~/Assets/client/js/jquery.slicknav.min.js"></script>
    <script src="~/Assets/client/js/owl.carousel.min.js"></script>
    <script src="~/Assets/client/js/jquery.nicescroll.min.js"></script>
    <script src="~/Assets/client/js/jquery.zoom.min.js"></script>
    <script src="~/Assets/client/js/jquery-ui.min.js"></script>
    <script src="~/Assets/client/js/main.js"></script>
    @RenderSection("jsFooter", required: false)
    <script>
        $.ajax({
            url: '/GioHang/SoLuong',
            type: 'GET',
            dataType: 'json',         
            success: function (response) {
                document.getElementById("spCount").innerHTML = response.data;
            }
        })
        function search(e) {
            window.location.href = '/SanPham/Index?Ten=' + $('#txtTen').val();
            e.preventDefault();
        }
    </script>
</body>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Xác nhận đăng xuất</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Xác nhận đăng xuất</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy bỏ</button>
                <a class="btn btn-primary" href="~/TaiKhoan/DangXuat">Đăng xuất</a>
            </div>
        </div>
    </div>
</div>