Source/NomNom/Areas/Admin/Controllers/SanPhamAdminController.cs
using NomNom.Models.BUS;
using NomNomConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NomNom.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SanPhamAdminController : Controller
    {
        // GET: Admin/SanPham
        public ActionResult Index()
        {
            var db = SanPhamBUS.DanhSachAdmin();
            return View(db);
        }

        // GET: Admin/SanPham/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/SanPham/Create
        public ActionResult Create()
        {
            ViewBag.loai_id = new SelectList(LoaiSanPhamBUS.DanhSach(), "id", "ten");
            ViewBag.thuonghieu_id = new SelectList(ThuongHieuBUS.DanhSach(), "id", "ten");
            return View();
        }

        // POST: Admin/SanPham/Create
        [HttpPost]
        public ActionResult Create(SanPham sp)
        {
            try
            {
                var hpf = HttpContext.Request.Files[0];
                if (hpf.ContentLength > 0)
                {
                    sp.hinhanh = sp.id+".png";
                    string fullpathwithfilename = "~/Images/" + sp.hinhanh ;
                    hpf.SaveAs(Server.MapPath(fullpathwithfilename));
                    
                }
                SanPhamBUS.Them(sp);
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Cập nhật csdl thất bại");
                //return RedirectToAction("error", "Shared");
                //return View();
            }
        }

        // GET: Admin/SanPham/Edit/5
        public ActionResult Edit(string id)
        {           
            var db = SanPhamBUS.ChiTiet(id);
            ViewBag.loai_id = new SelectList(LoaiSanPhamBUS.DanhSach(), "id", "ten", db.loai_id);
            ViewBag.thuonghieu_id = new SelectList(ThuongHieuBUS.DanhSach(), "id", "ten", db.thuonghieu_id);
            return View(db);
        }

        // POST: Admin/SanPham/Edit/5
        [HttpPost]
        public ActionResult Edit(SanPham sp)
        {
            try
            {
                sp.hinhanh = sp.id + ".png";
                var hpf = HttpContext.Request.Files[0];
                if (hpf.ContentLength > 0)
                {
                    sp.hinhanh = sp.id + ".png";
                    string fullpathwithfilename = "~/Images/" + sp.hinhanh;
                    hpf.SaveAs(Server.MapPath(fullpathwithfilename));
                }    
                SanPhamBUS.CapNhat(sp);             
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Cập nhật csdl thất bại");
                //return View();
            }
        }

        // GET: Admin/SanPham/Delete/5
        public ActionResult Delete(string id)
        {
            var db = SanPhamBUS.ChiTiet(id);
            ViewBag.loai_id = new SelectList(LoaiSanPhamBUS.DanhSach(), "id", "ten", db.loai_id);
            ViewBag.thuonghieu_id = new SelectList(ThuongHieuBUS.DanhSach(), "id", "ten", db.thuonghieu_id);
            return View(db);
        }

        // POST: Admin/SanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(SanPham sp)
        {
            try
            {
                sp.hinhanh = sp.id + ".png";
                sp.tinhtrang = 0;
                SanPhamBUS.CapNhat(sp);
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Cập nhật csdl thất bại");
                //return View();
            }
        }
    }
}

Source/NomNom/Areas/Admin/Views/SanPhamAdmin/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<style>
    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #2a9fd6;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

  
</style>


    <h3>Thêm Sản phẩm</h3>

    <div style="width:50%;margin:auto">
        @using (Html.BeginForm("Create", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <label for="id">Mã sản phẩm</label>
        <input type="text" id="id" name="id" style="background-color:#5d5e63" placeholder="Mã sản phẩm.." required>
        <label for="ten">Tên sản phẩm</label>
        <input type="text" id="ten" name="ten" style="background-color:#5d5e63" placeholder="Tên sản phẩm.." required>
        <label for="hinhanh">Hình ảnh</label>
        <input type="file" id="hinhanh" name="hinhanh" onchange="previewfile();" />
        <div>
            <label>Loại sản phẩm</label>
            @Html.DropDownList("loai_id", null, new { @style = "background-color:#5d5e63" })
        </div>
        <div>
            <label>Thương hiệu</label>
            @Html.DropDownList("thuonghieu_id", null, new { @style = "background-color:#5d5e63" })
        </div>    
        <label for="thongtin">Thông tin</label>
        <textarea required id="thongtin" name="thongtin" placeholder="Thông tin sản phảm.." style="width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        background-color:#5d5e63;
        height:150px"></textarea>
        <label for="giaban">Giá bán</label>
        <input type="text" id="giaban" name="giaban" style="background-color:#5d5e63" placeholder="Giá bán.." required>
        <label for="tinhtrang">Tình trạng</label>
        <select id="tinhtrang" name="tinhtrang" style="background-color:#5d5e63" required>
            <option value="0">Khóa</option>
            <option selected value="1">Không khóa</option>
        </select>

        <input type="submit" value="Thêm sản phẩm">
}
    </div>

Source/NomNom/Areas/Admin/Views/SanPhamAdmin/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}


<style>
    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #2a9fd6;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }
</style>


<h3>Sửa Sản phẩm</h3>

<div style="width:50%;margin:auto">
    @using (Html.BeginForm("Delete", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <label for="id">Mã sản phẩm</label>
        <input type="text" id="id" name="id" style="background-color:#5d5e63" placeholder="Mã sản phẩm.." required value="@Model.id" readonly>
        <label for="ten">Tên sản phẩm</label>
        <input type="text" id="ten" name="ten" style="background-color:#5d5e63" placeholder="Tên sản phẩm.." required value="@Model.ten" readonly>
        <label for="hinhanh">Hình ảnh</label>
        <img src="~/Images/@Model.hinhanh" style="width:200px;height:200px" />
        <div>
            <label>Loại sản phẩm</label>
            @Html.DropDownList("loai_id", null, new { @style = "background-color:#5d5e63" })
        </div>
        <div>
            <label>Thương hiệu</label>
            @Html.DropDownList("thuonghieu_id", null, new { @style = "background-color:#5d5e63" })
        </div>
        <label for="thongtin">Thông tin</label>
        <textarea readonly required id="thongtin" name="thongtin" placeholder="Thông tin sản phảm.." style="width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        background-color:#5d5e63;
        height:150px">@Model.thongtin</textarea>
        <label for="giaban">Giá bán</label>
        <input type="text" id="giaban" name="giaban" style="background-color:#5d5e63" placeholder="Giá bán.." required value="@Model.giaban" readonly>
        <label for="tinhtrang">Tình trạng</label>
        <select id="tinhtrang" name="tinhtrang" style="background-color:#5d5e63" required>

            <option selected value="0">Khóa</option>
        </select>

        <input type="submit" value="Xác nhận xóa">
    }
</div>

Source/NomNom/Areas/Admin/Views/SanPhamAdmin/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

<h2>Edit</h2>

Source/NomNom/Areas/Admin/Views/SanPhamAdmin/Index.cshtml
@using NomNom.Models.BUS
@model IEnumerable<NomNomConnection.SanPham>
    @{
        ViewBag.Title = "Index";
        Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
    }
    <head>
        <style>
            table {
                border-collapse: collapse;
                width: 70%;
                margin: auto;
            }

            th, td {
                text-align: center;
                padding: 8px;
            }

            tr:nth-child(even) {
                background-color: #5d5e63
            }

            th {
                background-color: #2a9fd6;
                color: white;
            }
        </style>
    </head>
    <body>

        <h2>Quản lí sản phẩm</h2>

        <table>
            <tr>
                <th>Mã sản phẩm</th>
                <th>Tên sản phẩm</th>
                <th>Hình ảnh</th>
                <th>Loại sản phẩm</th>
                <th>Thương hiệu</th>
                <th>Thông tin</th>
                <th>Giá bán</th>
                <th>Tình trạng</th>
                <th colspan="2">
                    <a href="@Url.Action("Create","SanPhamAdmin")"><img src="~/Images/AddIcon.png" /></a">
                </th>
            </tr>
            @foreach(var sp in Model)
            {
            <tr>
                <td>@sp.id</td>
                <td>@sp.ten</td>
                <td><img src="~/Images/@sp.hinhanh" style="width:50px;height:50px"/></td>
                <td>@sp.loai_id</td>
                <td>@sp.thuonghieu_id</td>
                <td>@sp.thongtin</td>
                <td>@sp.giaban</td>
                <td>@sp.tinhtrang</td>
                <td><a href="@Url.Action("Edit","SanPhamAdmin",new { id=sp.id})"><img src="~/Images/EditIcon.png" /></a></td>
                <td><a href="@Url.Action("Delete","SanPhamAdmin",new { id=sp.id})"><img src="~/Images/DeleteIcon.png" /></a></td>
            </tr>
            }
        </table>

    </body>