Source/NomNom/Models/TaiKhoan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NomNom.Models
{
    public class TaiKhoan: BaseModel
    {
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
    }
}

Source/NomNom/Models/TaiKhoans/TaiKhoan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NomNom.Models.TaiKhoans
{
    public class TaiKhoan: BaseModel
    {
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public int ChucVuID { get; set; }
        public string Ten { get; set; }
        public string Ho { get; set; }
        public DateTime? NgaySinh { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public bool IsBan { get; set; }
        public string Avatar { get; set; }
    }
}

Source/NomNom/Models/TaiKhoans/TaiKhoanDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NomNom.Models.TaiKhoans
{
    public class TaiKhoanDTO: Entity<int>
    {
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public int ChucVuID { get; set; }
        public string ChucVuTen { get; set; }
        public string Ten { get; set; }
        public string Ho { get; set; }
        public DateTime? NgaySinh { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public bool IsBan { get; set; }
        public string Avatar { get; set; }
    }
}

Source/NomNom/Models/TaiKhoans/TaiKhoanFilter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NomNom.Models.TaiKhoans
{
    public class TaiKhoanFilter
    {
        public string TenTaiKhoan { get; set; }
        public int ChucVuID { get; set; }
        TaiKhoanFilter()
        {
            TenTaiKhoan = null;
            ChucVuID = 0;
        }
    }
}

Source/NomNom/Models/TaiKhoans/TaiKhoanInput.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NomNom.Models.TaiKhoans
{
    public class TaiKhoanInput:Entity<int>
    {
        [Required(ErrorMessage = "Vui lòng nhập tên tài khoản")]
        [Display(Name="Tài khoản")]
        public string TenTaiKhoan { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "Vui lòng xác nhận mật khẩu")]
        [Display(Name = "Nhập lại mật khẩu")]
        public string MatKhau2 { get; set; }
        [Display(Name = "Chức vụ")]
        public int ChucVuID { get; set; }
        [Display(Name = "Tên")]
        public string Ten { get; set; }
        [Display(Name = "Họ")]
        public string Ho { get; set; }
        [Display(Name = "Ngày sinh")]
        public DateTime? NgaySinh { get; set; }
        [Required(ErrorMessage = "vui lòng nhập địa chỉ Email")]
        [Display(Name = "Địa chỉ Email")]
        public string Email { get; set; }
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }
        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }
        [Display(Name = "You won't see this")]
        public bool IsBan { get; set; }
        [Display(Name = "Ảnh đại diện")]
        public string Avatar { get; set; }
    }
}

Source/NomNom/Areas/Admin/Controllers/TaiKhoanController.cs
using NomNom.DAL;
using NomNom.Models.TaiKhoans;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NomNom.Areas.Admin.Controllers
{
    public class TaiKhoanController : BaseController
    {
        // GET: Admin/TaiKhoan
        public ActionResult Index()
        {
            var dal = new TaiKhoanDAL();
            return View(dal.GetTaiKhoan(null));
        }
        public ActionResult Khoa(int Id)
        {
            var dal = new TaiKhoanDAL();
            var result = dal.Ban(Id, true);
            return Redirect("/Admin/TaiKhoan");
        }
        public ActionResult MoKhoa(int Id)
        {
            var dal = new TaiKhoanDAL();
            var result = dal.Ban(Id, false);
            return Redirect("/Admin/TaiKhoan");
        }
        public ActionResult ChiTiet(int Id)
        {
            var dal = new TaiKhoanDAL();
            var result = dal.GetForView(Id);
            if (result!=null)
                return View(result);
            return Redirect("/Admin/TaiKhoan");
        }
    }
}

Source/NomNom/Controllers/TaiKhoanController.cs
using NomNom.Common;
using NomNom.DAL;
using NomNom.Models.TaiKhoans;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NomNom.Controllers
{
    public class TaiKhoanController : BaseController
    {
        // GET: TaiKhoan
        public ActionResult Index()
        {
            var user = (UserLogin)Session[NomNom.Common.CommonConstants.USER_SESSION];
            var dal = new TaiKhoanDAL();
            var input = dal.GetForEdit(user.UserID);
            return View(input);
        }
        [HttpGet]
        public ActionResult DoiMatKhau()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DoiMatKhau(FormCollection form)
        {
            if (ModelState.IsValid)
            {
                string MatKhauCu = form["MatKhauCu"].ToString();
                string MatKhauMoi = form["MatKhauMoi"].ToString();
                string MatKhau2 = form["MatKhau2"].ToString();
                if (MatKhauMoi!=MatKhau2)
                    ModelState.AddModelError("", "Mật khẩu không trùng khớp");
                else
                {
                    var dal = new TaiKhoanDAL();
                    var userID = ((UserLogin)Session[NomNom.Common.CommonConstants.USER_SESSION]).UserID;
                    var result = dal.DoiMatKhau(userID, MatKhauCu, MatKhauMoi);
                    if (result == CommonConstants.DOI_MAT_KHAU_THANH_CONG)
                        return Redirect("/TaiKhoan");
                    if (result == CommonConstants.DOI_MAT_KHAU_MAT_KHAU_MOI_DUOI_8)
                        ModelState.AddModelError("", "Mật khẩu mới phải ít nhất 8 kí tự");
                    if (result ==CommonConstants.DOI_MAT_KHAU_MAT_KHAU_CU_KHONG_DUNG)
                        ModelState.AddModelError("", "Mật khẩu cũ không chính xác");
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult CapNhat()
        {
            var user = (UserLogin)Session[NomNom.Common.CommonConstants.USER_SESSION];
            var dal = new TaiKhoanDAL();
            var input = dal.GetForEdit(user.UserID);
            if (input != null)
                return View(input);


            return Redirect("/TaiKhoan/Index");
        }
        [HttpPost]
        public ActionResult CapNhat(TaiKhoanInput input)
        {
            var session = Session[NomNom.Common.CommonConstants.USER_SESSION];
            if (session != null) {
                var user = (UserLogin)session;
               
                    try
                    {
                        var hpf = HttpContext.Request.Files[0];
                        if (hpf.ContentLength > 0)
                        {
                            user.Avatar = input.Avatar = "/Assets/image/avatar/"+"USERAVATAR_" +user.UserID+"_"+user.UserName+".jpg";
                            string fullpathwithfilename = "~"+input.Avatar;
                            hpf.SaveAs(Server.MapPath(fullpathwithfilename));
                        }                     
                    }
                    catch
                    {
                        return Content("Có lỗi xảy ra");
                    }
                
                var dal = new TaiKhoanDAL();
                input.Id = user.UserID;
                var result = dal.UpdateThongTin(input);
                if (result == 1)
                {
                    Session.Add(CommonConstants.USER_SESSION, user);
                    return Redirect("/TaiKhoan");
                }
            }
            return View();
        }
        public ActionResult DangXuat()
        {
            Session.Abandon();
            return Redirect("~/home");
        }
    }
}

Source/NomNom/Views/TaiKhoan/CapNhat.cshtml
@model NomNom.Models.TaiKhoans.TaiKhoanInput
@{
    ViewBag.Title = "Tài khoản - Cập nhật";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-info shadow mb-4" style="width:500px;margin:auto;margin-top:20px">
    <div class="panel-heading" style="background-color: #282828;padding: 10px 15px;color: #ffffff;">
        <div class="panel-title" style="font-size: 16px;color: inherit;">Cập nhật thông tin</div>
    </div>
    @using (Html.BeginForm("CapNhat", "TaiKhoan", FormMethod.Post, new { @class = "login-form" , enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px">
            <div class="form-row" style="margin-left:20px;width:200px;height:200px">
                @if (Model != null && Model.Avatar != null && Model.Avatar != "")
                {
                    <img id="Avatar" style="object-fit:contain" src="@Model.Avatar" />
                }
                else
                {
                    <img id="Avatar" style="object-fit:contain" src="~/Assets/image/NoImage.png" />
                }
            </div>
            <div class="col-7 form-row" style="margin-left:30px">
                <div class="w-100">@Html.LabelFor(model => model.Avatar)</div>
                <div class="w-100">
                    <input type="file" id="hinhanh" name="hinhanh" onchange="previewfile();" />
                </div>
                <div class="w-100">@Html.LabelFor(model => model.Ho)</div>
                <div class="w-100">@Html.TextBoxFor(model => model.Ho, new { @class = "form-control" })</div>
                <div class="w-100">@Html.LabelFor(model => model.Ten)</div>
                <div class="w-100">@Html.TextBoxFor(model => model.Ten, new { @class = "form-control" })</div>
            </div>
        </div>
        <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px">
            <div class="col-6 form-row">
                <div class="w-100">@Html.LabelFor(model => model.DiaChi)</div>
                <div class="w-100">@Html.TextBoxFor(model => model.DiaChi, new { @class = "form-control" })</div>
            </div>
            <div class="col-6 form-row" style="margin-left:20px">
                <div class="w-100">@Html.LabelFor(model => model.NgaySinh)</div>
                <div class="w-100">@Html.TextBoxFor(model => model.NgaySinh, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control" })</div>
            </div>
        </div>
        <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px;margin-bottom:20px">
            <div class="col-6 form-row">
                <div class="w-100">@Html.LabelFor(model => model.Email)</div>
                <div class="w-100">@Html.TextBoxFor(model => model.Email, new { @class = "form-control" })</div>
            </div>
            <div class="col-6 form-row" style="margin-left:20px">
                <div class="w-100">@Html.LabelFor(model => model.SDT)</div>
                <div class="w-100">@Html.TextBoxFor(model => model.SDT, new { @class = "form-control" })</div>
            </div>
        </div>
        <div class="form-row" style="margin-top:10px;margin-bottom:10px">
            <input type="submit" value="Xác nhận" class="btn btn-primary" style="margin:auto" />
        </div>
    }



</div>

Source/NomNom/Views/TaiKhoan/DoiMatKhau.cshtml
@{
    ViewBag.Title = "Tài khoản - Đổi mật khẩu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-info shadow mb-4" style="width:500px;margin:auto;margin-top:20px">
    <div class="panel-heading" style="background-color: #282828;padding: 10px 15px;color: #ffffff;">
        <div class="panel-title" style="font-size: 16px;color: inherit;">Cập nhật thông tin</div>
    </div>
    @using (Html.BeginForm("DoiMatKhau", "TaiKhoan", FormMethod.Post, new { @class = "login-form" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px">
            <div class="w-100"><label for="MatKhauCu">Mật khẩu cũ</label></div>
            <div class="w-100"><input name="MatKhauCu" type="password" id="MatKhauCu" required /></div>
        </div>
        <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px">
            <div class="w-100"><label for="MatKhauMoi">Mật khẩu mới</label></div>
            <div class="w-100"><input name="MatKhauMoi" type="password" id="MatKhauMoi" required /></div>
        </div>
        <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px">
            <div class="w-100"><label for="MatKhau2">Xác nhận mật khẩu</label></div>
            <div class="w-100"><input name="MatKhau2" type="password" id="MatKhau2" required /></div>
        </div>

        <div class="form-row" style="margin-top:10px;margin-bottom:10px">
            <input type="submit" value="Xác nhận" class="btn btn-primary" style="margin:auto" />
        </div>
    }



</div>

Source/NomNom/Views/TaiKhoan/Index.cshtml
@model NomNom.Models.TaiKhoans.TaiKhoanInput
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-info shadow mb-4" style="width:500px;margin:auto;margin-top:20px">
    <div class="panel-heading" style="background-color: #282828;padding: 10px 15px;color: #ffffff;">
        <div class="panel-title" style="font-size: 16px;color: inherit;">Thông tin tài khoản</div>
    </div>
            <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px">
                <div class="col-6 form-row">
                    <a href="/TaiKhoan/CapNhat"><button type="button" class="btn btn-dark">Cập nhật thông tin</button></a>
                </div>
                <div class="col-6 form-row">
                    <a href="/TaiKhoan/DoiMatKhau"><button type="button" class="btn btn-dark">Đổi mật khẩu</button></a>
                </div>
            </div>
            <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px">
                    <div class="form-row" style="margin-left:20px;width:200px;height:200px">
                        @if (Model!=null&&Model.Avatar != null&&Model.Avatar!="")
                        {
                            <img id="Avatar" style="object-fit:contain" src="@Model.Avatar" />
                        }
                        else
                        {
                            <img id="HinhAnh" style="object-fit:contain" src="~/Assets/image/NoImage.png" />
                        }
                    </div>
                    <div class="col-7 form-row" style="margin-left:30px">
                        <div class="w-100"><label for="TenTaiKhoan">Tên tài khoản</label></div>
                        <div class="w-100"><input id="TenTaiKhoan" class="form-control" readonly value="@Model.TenTaiKhoan" /></div>               
                        <div class="w-100"><label for="HoTen">Họ tên</label></div>
                        <div class="w-100"><input id="HoTen" class="form-control" readonly value="@Model.Ho @Model.Ten" /></div>
                    </div>               
                </div>
            <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px">
                <div class="col-6 form-row">
                    <div class="w-100"><label for="DiaChi">Địa chỉ</label></div>
                    <div class="w-100"><input id="DiaChi" class="form-control" readonly value="@Model.DiaChi" /></div>                   
                </div>
                <div class="col-6 form-row" style="margin-left:20px">
                    <div class="w-100"><label for="NgaySinh">Ngày sinh</label></div>
                    @if (Model.NgaySinh != null)
                    {
                        <div class="w-100"><input id="NgaySinh" class="form-control" readonly value="@Model.NgaySinh.Value.ToString("dd/M/yyyy")" /></div>
                    }
                    else
                    {
                         <div class="w-100"><input id="NgaySinh" class="form-control" readonly value="Không có thông tin" /></div>
                    }
                </div>
            </div>
            <div class="col-11 d-flex justify-content-start align-items-start" style="margin-top:10px;margin-bottom:20px">          
                <div class="col-6 form-row">
                    <div class="w-100"><label for="Email">Địa chỉ Email</label></div>
                    <div class="w-100"><input id="Email" class="form-control" readonly value="@Model.Email" /></div>
                </div>
                <div class="col-6 form-row" style="margin-left:20px">
                    <div class="w-100"><label for="SDT">Số điện thoại</label></div>
                    <div class="w-100"><input id="SDT" class="form-control" readonly value="@Model.SDT" /></div>
                </div>
            </div>
       
       


</div>