Source/NomNom/Controllers/DangNhapController.cs
using NomNom.Common;
using NomNom.DAL;
using NomNom.Models.TaiKhoans;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NomNom.Controllers
{
    public class DangNhapController : Controller
    {
        // GET: DangNhap
        public ActionResult Index()
        {
            if (Session[NomNom.Common.CommonConstants.USER_SESSION] == null)
                return View();
            return Redirect("~/home");
        }
        public ActionResult DangNhapThanhCong()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(TaiKhoanInput input)
        {
            if (input.MatKhau != null && input.TenTaiKhoan != null)
            {
                var dal = new TaiKhoanDAL();
                var result = dal.Login(input.TenTaiKhoan, input.MatKhau);
                if (result == CommonConstants.DANG_KY_TAI_KHOAN_THANH_CONG)
                {
                    var Login = new UserLogin();
                    Login.UserID = dal.GetId(input.TenTaiKhoan);
                    Login.UserName = input.TenTaiKhoan;
                    var tk = dal.GetForView(Login.UserID);
                    Login.ChucVuID = tk.ChucVuID;
                    if (tk.Ten != null && tk.Ten != "")
                        Login.Name = tk.Ten;
                    else
                        Login.Name = tk.TenTaiKhoan;
                    if (tk.Avatar != null && tk.Avatar != "")
                        Login.Avatar = tk.Avatar;
                    else
                        Login.Avatar = "/assets/image/NoImage.png";
                    Session.Add(CommonConstants.USER_SESSION, Login);
                    return View("DangNhapThanhCong");
                }
                else
                {
                    if (result == CommonConstants.DANG_NHAP_MAT_KHAU_KHONG_DUNG)
                        ModelState.AddModelError("", "Mật khẩu không đúng");
                    else if (result == CommonConstants.DANG_NHAP_TAI_KHOAN_KHONG_TON_TAI)
                        ModelState.AddModelError("", "Tài khoản không tồn tại");
                    else if (result == CommonConstants.DANG_NHAP_TAI_KHOAN_BI_KHOA)
                        ModelState.AddModelError("", "Tài khoản đã bị khóa");
                }
            }            
            return View("Index");
        }
    }
}

Source/NomNom/Views/DangNhap/DangNhapThanhCong.cshtml
@{
    ViewBag.Title = "Đăng nhập thành công";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<center>Đăng nhập thành công. Bấm vào <a href="~/Home/Index"><span>đây</span></a> để quay về trang chủ</center>

Source/NomNom/Views/DangNhap/Index.cshtml
@model NomNom.Models.TaiKhoans.TaiKhoanInput
@{
    ViewBag.Title = "Đăng nhập";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-info shadow mb-4" style="width:500px;margin:auto;margin-top:20px">
    <div class="panel-heading" style="background-color: #282828;padding: 10px 15px;color: #ffffff;">
        <div class="panel-title" style="font-size: 16px;color: inherit;">Đăng nhập</div>
    </div>
    @using (Html.BeginForm("Login", "DangNhap", FormMethod.Post, new { @class = "login-form" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   
        <div class="col-11 d-flex justify-content-center" style="margin-top:10px">
            <div class="col-11 form-row w-100">
                <div class="w-100">@Html.LabelFor(model => model.TenTaiKhoan)</div>
                <div class="w-100">@Html.TextBoxFor(model => model.TenTaiKhoan, new { @class = "form-control" })</div>
                <div class="w-100">@Html.ValidationMessageFor(model => model.TenTaiKhoan, "", new { @class = "text-danger" })</div>
            </div>
        </div>
        <div class="col-11 d-flex justify-content-center" style="margin-top:10px">
            <div class="col-11 form-row w-100">
                <div class="w-100">@Html.LabelFor(model => model.MatKhau)</div>
                <div class="w-100">@Html.TextBoxFor(model => model.MatKhau, new { @type = "password", @class = "form-control" })</div>
                <div class="w-100">@Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })</div>
            </div>
        </div>
       

        <div class="form-row" style="margin-top:10px;margin-bottom:10px">
            <input type="submit" value="Xác nhận" class="btn btn-dark" style="margin:auto" />
        </div>
    }
</div>